### ISSUE TITLE
Qual a senha?

### ISSUE THREAD

**Issue by ribafs** [flavianohonorato/cakephp3-skeleton#1]
Flávio, me parece legal, mas não está faltando a senha?

**Comment by flavianohonorato** [comment]
A senha você pode gerar no arquivo de seed, você só precisa modificar para suas preferências e rodar o seed.

**Comment by flavianohonorato** [comment]
https://github.com/flavianohonorato/cakephp3-skeleton/blob/master/config/Seeds/UsersSeed.php

**Comment by ribafs** [comment]
Muito grato meu caro. 

Em 28/10/2016 16:47, Flaviano Honorato escreveu: 

> https://github.com/flavianohonorato/cakephp3-skeleton/blob/master/config/Seeds/UsersSeed.php [1] 
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

## 

Colaborar é ser Humano!

## Links:

[1]
https://github.com/flavianohonorato/cakephp3-skeleton/blob/master/config/Seeds/UsersSeed.php
[2]
https://github.com/flavianohonorato/cakephp3-skeleton/issues/1#issuecomment-256998628
[3]
